### PR TITLE
Fix path to distros.toml

### PR DESCRIPTION
**Pull request by AMDmi3**

### CODE REVIEW

**Comment by AMDmi3** [comment]
Btw, big thanks for respecting ToS when polling Repology.

FYI Repology also supports [this](https://repology.org/badge/versions-matrix.svg?projects=debhelper%3E=13.3.4,linux%3E=5.10.218,glibc%3E=2.28,gcc%3E=8.3,llvm,binutils%3E=2.30,python%3E=3.11,meson%3E=0.56.2,ninja%3E=1.8.2,cjson%3E=1.7.14,uthash%3E=2.1,mbedtls%3E=3.5.1,protobuf-c%3E=1.3.0,python:tomli,python:tomli-w,python:cryptography,python:pyelftools,protobuf,python:sphinx%3E=3.4.3,python:docutils,python:sphinx-rtd-theme,python:breathe,python:recommonmark,python:furo,libcbor%3E=0.5.0,curl,cmake), but that's experimental and your approach is more practical for now.

**Comment by woju** [comment]
Thanks for fix.

I'm sorry for my past hammering, I wrote this as quick contraption back when I think there was no `/project`, only `/projects`, and I noticed ToS only lately, when you started blocking httpx.

Regarding `version-matrix.svg`, thanks, I didn't know about it. I'd consider using it if it allowed for limiting the list of repositories (`&repositories=...`?). My use case is to package a single app for a limited set of very popular distros, and I'd like to know when we can update a dependency. Full list of all known repos is of a little use for me.

Alternatively I could contribute my little contraption for wider use at repology. If you'd be interested, feel free to contact me (woju invisiblethingslab com).

**Comment by AMDmi3** [comment]
> I'm sorry for my past hammering

I've never witnessed it, so there was probably no much problem.

> Regarding version-matrix.svg, thanks, I didn't know about it. I'd consider using it if

As mentioned, it's rather experimental and also heavy on database load (hopefully some time that will be improved), so your implementation looks more viable now.

> My use case is to package a single app for a limited set of very popular distros, and I'd like to know when we can update a dependency. Full list of all known repos is of a little use for me.

Not sure about that, my policy is to unconditionally provide pervasive view. There's an option to exclude EoLed repositories though.

> Alternatively I could contribute my little contraption for wider use at repology. If you'd be interested, feel free to contact me (woju invisiblethingslab com).

For the record, I prefer to communicate publicly. Well that sounds interesting, which are action items? After a quick glance it looks generic enough for me to be set up for any set of repository/dependency combinations so can probably used as it is, and I can put a link to it in Tools section. Any more ideas?

**Comment by woju** [comment]
> For the record, I prefer to communicate publicly.

Not a problem, but I'd like to keep this PR on topic, so I'll create an issue instead and will answer shortly.

**Pull request merged**
